# Generated by Django 3.0 on 2020-08-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='presidente',
            new_name='leadership',
        ),
    ]
