# Generated by Django 3.0 on 2020-09-04 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0009_auto_20200904_1332'),
        ('parties', '0003_auto_20200904_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='leadership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadership.Leadership'),
        ),
    ]
