# Generated by Django 3.0 on 2020-09-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='historic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
