# Generated by Django 3.0 on 2020-07-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
