# Generated by Django 3.0 on 2020-08-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_auto_20200723_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='handling',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
