# Generated by Django 3.0 on 2020-09-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_auto_20200827_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
