# Generated by Django 3.0 on 2020-09-02 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_auto_20200801_0218'),
        ('leadership', '0003_auto_20200902_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='positions.Position'),
        ),
    ]
