# Generated by Django 3.0 on 2020-09-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0004_auto_20200902_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='office',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
