# Generated by Django 3.0 on 2020-09-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0005_leadership_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='pendency',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
