# Generated by Django 3.0 on 2020-09-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0006_leadership_pendency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='cpf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='rg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
