# Generated by Django 3.0 on 2020-09-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0007_auto_20200903_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='nickname',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
