# Generated by Django 3.0 on 2020-07-29 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('positions', '0002_auto_20200723_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authoritie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('genre', models.CharField(max_length=25, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('birth', models.DateTimeField()),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='positions.Position')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
