# Generated by Django 3.0 on 2020-07-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritie',
            name='genre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='authoritie',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
