# Generated by Django 3.0 on 2020-07-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0002_auto_20200729_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritie',
            name='birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='authoritie',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
