# Generated by Django 3.0 on 2020-07-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0003_auto_20200729_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authoritie',
            old_name='created',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='authoritie',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='authoritie',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='authoritie',
            name='genre',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
