# Generated by Django 3.0 on 2020-07-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0004_auto_20200730_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoritie',
            name='genre',
        ),
    ]
