# Generated by Django 3.0 on 2020-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0005_remove_authoritie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritie',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
