# Generated by Django 3.0 on 2020-07-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0006_auto_20200730_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoritie',
            name='email',
        ),
        migrations.RemoveField(
            model_name='authoritie',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='authoritie',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
