# Generated by Django 3.0 on 2020-08-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0008_auto_20200730_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritie',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
