# Generated by Django 3.0 on 2020-08-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='recurrence',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
