# Generated by Django 3.0 on 2020-08-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
