# Generated by Django 3.0 on 2020-08-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='leadership',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
