# Generated by Django 3.0 on 2020-08-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200831_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location_reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
