# Generated by Django 3.0 on 2020-08-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_location_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
