# Generated by Django 3.0 on 2020-08-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20200831_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rg',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
