# Generated by Django 3.0 on 2020-09-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20200831_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='old_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
