# Generated by Django 3.0 on 2020-07-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('phone_number', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=80)),
                ('street', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
