# Generated by Django 3.0 on 2020-08-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20200731_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
