# Generated by Django 3.0 on 2020-08-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institution_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
