# Generated by Django 3.0 on 2020-08-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20200821_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
